### PR TITLE
add "WebPageTest Bulk Tester" tool - fix #653

### LINKED ISSUE #653: WPT-Bulk-Tester
https://github.com/andydavies/WPT-Bulk-Tester

not sure how to implement this, though.

### PR DESCRIPTION
**Pull request by marcobiedermann**

### CODE REVIEW

**Comment by stefanjudis** [comment]
Maybe I'm wrong, but this is not JavaScript isn't it?

Actually it's `Google App Script`.

**Comment by marcobiedermann** [comment]
> Google Apps Script is a JavaScript cloud scripting language that provides easy ways to automate tasks across Google products and third party services and build web applications.

**Comment by stefanjudis** [comment]
@marcobiedermann 

But the script tag is for snippets or libraries I can use inside of my browser.

I can't do this with this, or?
So it would be the only "javascript" tool that I can't actually use?

**Comment by marcobiedermann** [comment]
I have another solution. We drop this tool but include [this article](http://calendar.perfplanet.com/2014/driving-webpagetest-from-a-google-docs-spreadsheet/) instead.

**Comment by stefanjudis** [comment]
I don't understand, what's the deal with adding the google `g` as platform?

Think of perf driven templates for Analytics ( which are out there ) or anything I can't even think of? ;)

**Comment by marcobiedermann** [comment]
Alright, we go with a nice little *g*

**Comment by marcobiedermann** [comment]
Actually the logo is an [arrow](http://en.wikipedia.org/wiki/Google_Apps_Script).

perf-tooling-webpage-test-bulk

**Comment by stefanjudis** [comment]
Cool! :+1:

**Pull request merged**
