### PR TITLE
:memo: New articles from the Dareboost team

### PR DESCRIPTION
**Pull request by borisschapira**
Hi there. Here are some of the best pieces from the Dareboost team. Some of them deal with topics that have already been discussed from a different angle. Others deal with subjects that are rarely dealt with (e. g. streaming). I have taken care to select some technical articles that do not specifically highlight the solution but may serve the whole community.

### CODE REVIEW

**Comment by marcobiedermann** [comment]
@borisschapira Wow, thank you Boris for all your articles.
It would be nicer to have one PR per post but this should also work for now!

**Comment by borisschapira** [comment]
A PR per post. Hold my hot chocolate.

**Comment by marcobiedermann** [comment]
@borisschapira Thanks man for creating all these pull requests!

**Comment by borisschapira** [comment]
You're welcome. I looked for a CONTRIBUTING.md, did'nt find one. Maybe that would be a little something to add?

**Comment by marcobiedermann** [comment]
@borisschapira We do have a [CONTRIBUTING.md](https://github.com/stefanjudis/perf-tooling/blob/master/.github/CONTRIBUTING.md)

**Comment by borisschapira** [comment]
Silly my, I've only looked at the root folder. My bad!

**Pull request closed without merging**
