### PR TITLE
Feature/78 travis

### LINKED ISSUE #78: Add Travis and build process
https://david-dm.org/ for dep checks

And CSSLint, JSHint and check for valid *.json files. :)

https://www.npmjs.org/package/gulp-jsonlint

### PR DESCRIPTION
**Pull request by marcobiedermann**
fix #78

### CODE REVIEW

**Comment by stefanjudis** [comment]
@marcobiedermann 

Hmm, build still failing?

And usually the `npm test` command is used for this kind of stuff. :)
When you need help - let me know. :)

**Comment by marcobiedermann** [comment]
@stefanjudis Yeah, I tried travis a bit but I am not that familiar with the setup. If you know, how to fix this feel free to adjust the configuration.

**Comment by stefanjudis** [comment]
@marcobiedermann 

Here we go - what I did:

- added a csslint gulp task
- added `npm test` command to package.json ( this is kind of default for node projects )

The key thing that was wrong, was that `grunt dev` is a task that will never finish. Travis deals afaik with exit status code. `0` always means "all cool" and anything else means, that s.th. went wrong.

That for the new `csslint` task fails hard in case of any error. :)

```
stefan @ stefan-mac: ~/sites/perf-tooling feature/78-travis (╯°□°)╯
> npm test                                                                                              [22:44:24]

> perf-tooling@1.0.0 test /Users/stefan/Sites/perf-tooling
> gulp test

[22:47:33] Using gulpfile ~/Sites/perf-tooling/gulpfile.js
[22:47:33] Starting 'csslint'...
[22:47:33] 1 error found in /Users/stefan/Sites/perf-tooling/less/main.css
[22:47:33] [L652:C1] Don't use IDs in selectors. Selectors should not contain IDs. (ids)
[22:47:33] 'csslint' errored after 152 ms
[22:47:33] Error in plugin 'gulp-csslint'
Message:
    CSSLint failed for main.css
npm ERR! Test failed.  See above for more details.
FAIL: 1
```

In case you've got any more errors - ping me. ;)

**Comment by stefanjudis** [comment]
Also waiting for this one:

https://github.com/rogeriopvl/gulp-jsonlint/pull/5

**Comment by marcobiedermann** [comment]
Looks great. I suggest that we tackle the linting warnings later. For now, I've updated csslint config.
`"duplicate-properties": false` and `"ids": false`. See: https://github.com/stefanjudis/perf-tooling/commit/0ffe350c9be0fce272481eb1bf2ac16fd170522e. With these settings, everything should work fine.

**Comment by stefanjudis** [comment]
Here we go! :tada:

**Pull request merged**
