### PR TITLE
adds ruby-jmeter gem

### PR DESCRIPTION
**Pull request by 90kts**
A Ruby based DSL for building JMeter test plans.

### CODE REVIEW

**Comment by marcobiedermann** [comment]
@90kts Thank you! :) Sorry for the delay. I've checked the repo and it seams that this tool is a ruby gem. I think it would make more sense to set the platform to ruby instead of CLI. What do you think? If you agree, I will look for a ruby icon.

**Comment by 90kts** [comment]
:+1:  perhaps?

**Comment by marcobiedermann** [comment]
blocked by #572

**Comment by marcobiedermann** [comment]
added PR for ruby icon #572. Would you mind, changing the platform from CLI to ruby? I am really sorry for asking you that late aber your request.

**Comment by 90kts** [comment]
done ..


Tim

**Comment by marcobiedermann** [comment]
@90kts :+1: Yey! Thank you man :)

**Comment by stefanjudis** [comment]
@marcobiedermann please set milestones in future. :)

**Pull request merged**
