### PR TITLE
Add mobile-friendly tool

### PR DESCRIPTION
**Pull request by denar90**
Add Mobile-Friendly Test API for Node.js lib - https://github.com/denar90/mobile-friendly

### CODE REVIEW

**Comment by stefanjudis** [comment]
Hey hey, thanks for your contribution. :) 

I'm not sure your tool is the best fit for perf-tooling, though.
As I see it it's not performing any web performance related tests and is more User Experience driven, am I wrong?

I'm up for more opinions. :) 

@radibit @marcobiedermann @ben-eb

**Comment by denar90** [comment]
Sounds reasonable. Feel free to close it if so :)

**Comment by marcobiedermann** [comment]
@denar90 Thank you Artem for your PR. Nice CLI for Google's Mobile Friendly Service but I have to agree with Stefan. The service is more about the user experience instead of performance optimization.

**Comment by stefanjudis** [comment]
But thanks @denar90. 👍 Keep it going!

**Comment by denar90** [comment]
Thanks for a feedback guys :)
Cool project btw 👍

**Comment by ben-eb** [comment]
Agreed, but great work! By the way you might want to consider using http://ghub.io/chalk for handling ANSI codes, it'd make your logging look much tidier. 🙂

**Comment by denar90** [comment]
Thanks. I just wanted this small lib to have less deps :)

**Pull request closed without merging**
