### PR TITLE
Feature/18 paid

### LINKED ISSUE #18: Implement property to show if it's paid or not

### PR DESCRIPTION
**Pull request by marcobiedermann**
fix #18 

@stefanjudis How do I print out if one of the platforms is paid or not?
This does not work and also feels not right :)

```
<h3><%= tool.name %><% if ( tool.bookmarklet.isPaid || tool.chrome.isPaid || tool.firefox.isPaid || tool.internetExplorer.isPaid || tool.safari.isPaid || tool.mac.isPaid || tool.windows.isPaid || tool.linux.isPaid || tool.cli.isPaid || tool.module.isPaid || tool.angular.isPaid || tool.grunt.isPaid || tool.gulp.isPaid || tool.illustrator.isPaid || tool.javascript.isPaid || tool.php.isPaid || tool.wordpress.isPaid || tool.service.isPaid ) { %><small>Paid</small><% } %></h3>
```

### CODE REVIEW

**Comment by stefanjudis** [comment]
@marcobiedermann there should be a helper function so that we can simply use `isPaid( tool )` I can provide that if you like?

**Comment by marcobiedermann** [comment]
@stefanjudis Yeah, that would be great, you can checkout `feature/18-paid`

**Comment by radibit** [comment]
@marcobiedermann @stefanjudis 

I assigned this to me in order to provide the helper function :smiley:

**Comment by radibit** [comment]
@marcobiedermann the `isPaid` helper function is created now. Can you please check the latest commit and confirm it's working as expected? Also the `<small>Paid</small>` element will required some additional styling. I will assign the issue back to you :blush:

**Comment by marcobiedermann** [comment]
I would first merge #713 if everything is fine. Otherwise we have to do things over and over again.

**Comment by stefanjudis** [comment]
Sure. Go ahead. :)

Marco Biedermann <notifications@github.com> schrieb am Mo., 25. Mai 2015
13:48:

**Comment by marcobiedermann** [comment]
@radibit Merged master into this branch. Could you take another look at it.
https://github.com/stefanjudis/perf-tooling/blob/27f8060bbc54544c0dd15f55c6f516acf766bafe/templates/partials/lists/tools.tpl#L29 Does not work propery

**Comment by radibit** [comment]
@marcobiedermann Thanks for indicating this bug. I just fixed it with the latest commit. Can you please verify and confirm :smiley:

**Comment by marcobiedermann** [comment]
@radibit Hmm, I actually tried this as well but is was not working for me. Anyway, not everything works fine.

perf-tooling-paid

+1 From my side. Feel free to hit this nice green button :)

**Comment by radibit** [comment]
> Anyway, not everything works fine.

@marcobiedermann Can you please clarify? Are there any other problems?

**Comment by marcobiedermann** [comment]
Sorry, typo.
*Now* everything works fine

**Comment by stefanjudis** [comment]
Anyone of you wants to press this button? :D

**Pull request merged**
