### PR TITLE
add an article "Introduction to WebP"

### PR DESCRIPTION
**Pull request by 1000ch**
I wrote up [an article](https://medium.com/@1000ch/introduction-to-webp-b593dfe1d1d1) about WebP by Google.

### CODE REVIEW

**Comment by stefanjudis** [comment]
Thx @1000ch. Will check it tomorrow.

**Comment by stefanjudis** [comment]
@1000ch 

Hey hey, I think we'll take it. Thanks for writing. :bowtie: 

But I think you mixed up the length and put in characters instead of words. I'd be happy to merge, when this is fixed. :)

**Comment by 1000ch** [comment]
@stefanjudis Thank you for taking :smile: Fixed the count so please confirm it :)

**Comment by stefanjudis** [comment]
Nice... :+1: 

Thanks for contributing. :) Will merge as soon as travis passed.

**Pull request merged**
