### PR TITLE
Add HTTP/2 Test by KeyCDN

### PR DESCRIPTION
**Pull request by brianleejackson**

### CODE REVIEW

**Comment by marcobiedermann** [comment]
@brianleejackson Thank you Brian, could you please add `.json` extension to your file?!
Otherwise, everything looks good to me :)

**Comment by stefanjudis** [comment]
@brianleejackson Just out of curiosity - how does KeyCDN figure that out? Having some issues with `is-http2` and false positives. :)

**Comment by brianleejackson** [comment]
@marcobiedermann Oops, sorry about that :) K, I have added the extension. @stefanjudis I am more on the marketing side :) but feel free to shoot us an email at support (at) keycdn.com with questions about HTTP/2 tool. Thanks guys!

**Comment by marcobiedermann** [comment]
@brianleejackson Perfect, thanks man :+1:

**Pull request merged**
