### PR TITLE
add "imgix" tool - fix #769

### LINKED ISSUE #769: imgix
https://www.imgix.com/imgix-js

### PR DESCRIPTION
**Pull request by marcobiedermann**
I've also added the `Java` library. I open up a ticket for adding a new icon to the tools.

### CODE REVIEW

**Comment by stefanjudis** [comment]
@marcobiedermann We don't have the java platform yet, or?

**Comment by marcobiedermann** [comment]
No haven't yet implemented the icon. Sorry for the inactivity but I am currently quite busy with school. I hope do get some work done next week

**Comment by stefanjudis** [comment]
No pressure. I'm just checking. ;)

Marco Biedermann <notifications@github.com> schrieb am Mi., 1. Juli 2015
23:57:

**Comment by stefanjudis** [comment]
:+1:

**Pull request merged**
