### PR TITLE
Feature/299 newsletter integration

### PR DESCRIPTION
**Pull request by marcobiedermann**
perf-tooling-newsletter

### CODE REVIEW

**Comment by stefanjudis** [comment]
@marcobiedermann nice - only email template setup is missing. :)

And if that's done - the automation. Great!

**Comment by stefanjudis** [comment]
@marcobiedermann 
I will merge this one tonight - and then we'll probably can send out our first newsletter on the weekend. :) :dancer:

**Comment by marcobiedermann** [comment]
Yey! Looking forward!

**Comment by stefanjudis** [comment]
I'll send you a test email in a few seconds. ;)

If you want to participate shout out. ;)

**Comment by stefanjudis** [comment]
Early stage though. Emails suck so bad. :(

**Pull request merged**
