### PR TITLE
add video "DevTools State of the Union" - fix #630

### LINKED ISSUE #630: DevTools state of the union
http://jqueryuk.com/2015/videos.php?s=devtools-state-of-the-union

### PR DESCRIPTION
**Pull request by marcobiedermann**

### CODE REVIEW

**Comment by stefanjudis** [comment]
I don't think this video will work, because of the vimeo settings. :(

**Comment by marcobiedermann** [comment]
We have to wait until the modal feature is implemented. Including the video via iframe works fine: http://jsfiddle.net/m412c0/aekn0gxr/

**Comment by marcobiedermann** [comment]
blocked by #644

**Comment by stefanjudis** [comment]
Hmm, but then still API data is not catched or?

We had this problem already once. Only remember it barely.

**Comment by marcobiedermann** [comment]
You could be right. I am not sure about it. Let's test it? We can remove this anyway.

**Comment by stefanjudis** [comment]
I'd push this one ofter current release, because then I can test it properly.

I'm really careful with API stuff.  Don't want to go into any risk.

**Comment by marcobiedermann** [comment]
Works fine on my local machine.
This is a screenshot of the video in the modal window.

perf-tooling-modal

**Comment by stefanjudis** [comment]
Alright let's see how the deploy goes then. :)

**Pull request merged**
