### PR TITLE
📝 add guessjs - fix #1363

### LINKED ISSUE #1363: Guess.js
[Guess.js](https://github.com/guess-js/guess) provides libraries & tools to simplify predictive data-analytics driven approaches to improving user-experiences on the web. This data can be driven from any number of sources, including analytics or machine learning models.

### PR DESCRIPTION
**Pull request by radibit**
# Hey there!

Thanks for contributing to perf-tooling!

Please make sure that you followed the following conventions:

- [x] your commits follow the [gitmoji](https://gitmoji.carloscuesta.me/) convention 
- [x] the build on travis succeeds
- [x] your changes align with the rules in the [CONTRIBUTING.MD](./CONTRIBUTING.md)

**Note:** For all commits dealing with resources, we decided to use the :memo: emoji for commit messages.

And that's it. Thanks! ;)

### CODE REVIEW

**Comment by stefanjudis** [comment]
Hmm not sure about this one tbh... It can be the base for performance tooling but guess js is right now not perf related or?

**Comment by radibit** [comment]
It uses a predictive-fetching workflow which improves perceived page load performance and user experience 🙂 

Sure, this initiative is as its beginning so I'd be also fine if we add it on a later stage when we can have even more arguments on the performance benefits of using it.

**Comment by stefanjudis** [comment]
> It uses a predictive-fetching workflow which improves perceived page load performance and user experience 🙂

Jep, but that's only one use case isn't it? Guess.js in general for enabling data-driven user-experiences on the web. Which means it can be used for perf stuff but isn't bound to it.

> - Predict the next page (or pages) a user is likely to visit and prefetch these pages, improving perceived page load performance and user happiness.
> - Predict the next piece of content (article, product, video) a user is likely to want to view and adjust or filter the user experience to account for this.
> - Predict the types of widgets an individual user is likely to interact with more (e.g games) and use this data to tailor a more custom experience.


E.g. https://github.com/guess-js/guess/tree/master/packages/webpack would be a performance tool based on guess.js.

I've got no strong feeling here, but adding guess.js would feel like adding webpack to me. Webpack can be used for performance improvements but it's purpose is module bundeling. :)

**Comment by radibit** [comment]
Ok, fair points. Let's see how this resource will be shaped in the future and then suggest adding more specific web performance related tools.

**Pull request closed without merging**
