### PR TITLE
clean up tools template

### PR DESCRIPTION
**Pull request by marcobiedermann**
I tried to clean up the tools template. Unfortunately I am not that into JavaScript and do not know how to fix it. I get `[TypeError: Cannot read property 'indexOf' of undefined]`.
The benefit of the clean up is, that it is easier to add new tools to it with less coding.

### CODE REVIEW

**Comment by radibit** [comment]
@marcobiedermann @stefanjudis 

Assigned to me so I can work on the problem described in the previous comment.

**Comment by radibit** [comment]
@marcobiedermann 
I just fixed the error and did a refactoring of the tools list and fuzzy templates, because of the new platforms config structure. At the moment the SVG icons names are generated dynamically based on the `platforms.name` property which means that some icon names need to be unified e.g. `icon-terminal` does not match `platforms : [ { name : 'cli' } ] `. Can you please have a look at the latest commit and adjust the required icon names?

@stefanjudis 
Can you please CR? Thanks.

**Comment by marcobiedermann** [comment]
@radibit Cool, thanks. Yes, you are right. I've also noticed that. I will rename some icons and check your commit if everything is working

**Comment by stefanjudis** [comment]
Great cleanup guys! :+1:

**Comment by marcobiedermann** [comment]
I renamed some icons and fixed merge conflicts.
Also I deleted the Internet Explorer icon because it is not used.
All seems good, so feel free to merge this. :)

**Pull request merged**
