### PR TITLE
New tool and updates

### PR DESCRIPTION
**Pull request by micmro**
I've added Request Map Generator and Performance-Analyser and fixed the repo of performance-bookmarklet, since I have moved it.

### CODE REVIEW

**Comment by marcobiedermann** [comment]
@micmro Thank you for your pull-request. Just two little things. Could you please add a newline at end of the files?!. Also the browser extension "Performance-Analyser" looks the same as [Perfmap](http://perf-tooling.today/tools#perfmap). I think we can merge these together.

**Comment by micmro** [comment]
Np. Fixed.

**Comment by stefanjudis** [comment]
@micmro 

Nice and thanks.
And btw good work on Request Map Generator! :+1:

**Comment by micmro** [comment]
Thanks, but Request Map Generator is actually not by me. It's by Simon Hearne (https://twitter.com/simonhearne).

I really liked it so I've added it.

Though the other ones are from me.

**Comment by stefanjudis** [comment]
Ahh okay. :)

> I really liked it so I've added it.

Yeah thanks - that's exactly the idea of perf-tooling. :tada:

**Pull request merged**
