### PR TITLE
Feature/critical css

### PR DESCRIPTION
**Pull request by marcobiedermann**
@stefanjudis
Do you have an idea how to add multiple sources for penthouse. I suggest creating individual css for each page and inline the corresponding css in the head.
I can not find any hints on the [penthouse](https://github.com/pocketjoso/penthouse) repo.

With grunt my setup looks like this:
```
critical: {
    options: {
      base: './',
      css: [
        '<%= config.source %>/css/style.css',
      ],
      width: 800,
      height: 600
    },
    files: {
      expand: true,
      cwd: '<%= config.source %>',
      dest: '<%= config.tmp %>/critical',
      src: '**/*.html',
      ext: '.css'
    }
  },
```

In this example I use critical instead of penthouse but critical does not support url / http input. They pretty much do the same job

### CODE REVIEW

**Comment by stefanjudis** [comment]
Wait? what is this? :)

I'm pretty sure that's hardy conflicting with

https://github.com/stefanjudis/perf-tooling/pull/609

**Comment by marcobiedermann** [comment]
Yeah, I've seen the work of @radibit but I am not sure, whether he covers inlining critical css

**Comment by stefanjudis** [comment]
Our CSS is gzipped not 3k large. This fits pretty much in the first round trip.

What else is included in the pending PR: 

- inlining all css as said 3K
- loading hashed CSS via loadCSS ( minified and crunched via build )
- setting cookie when it went into cache
- serving of no inline css anymore with server side cookie logic

If you want to include penthouse to save this 1K unfortunately you have to wait. Sorry. :(

@radibit 's PR is pending because the SVG icons needs to be hashed in new way ( which is also included in this PR ) - they went into master first.

**Comment by marcobiedermann** [comment]
Alright, thanks for the clarification. Let's wait for @rabit 's pending request and see how we further optimize this baby :)

**Comment by radibit** [comment]
So as I understand my PR is kind of a blocker for this one. Sorry about that, I'm a little bit busy these days, but hopefully I will finish #609 through this weekend.

**Comment by stefanjudis** [comment]
@radibit 

All good. Just working in parallel. :)

**Comment by stefanjudis** [comment]
@marcobiedermann So you'll give this still a shot?

There are pretty sure hard conflicts. :(

**Comment by stefanjudis** [comment]
@marcobiedermann ping.

**Comment by marcobiedermann** [comment]
Will tackle this tomorrow

**Comment by marcobiedermann** [comment]
This is not finished. Just had to push my version

**Comment by marcobiedermann** [comment]
This is not done yet. Will continue then my server is up again

**Pull request closed without merging**
