### PR TITLE
Add Tracking Real World Web Performance to Course Section

### PR DESCRIPTION
**Pull request by nikmd23**

### CODE REVIEW

**Comment by stefanjudis** [comment]
:+1:

**Comment by nikmd23** [comment]
Thanks!

**Comment by stefanjudis** [comment]
Sorry for the huuuuuuge delay. :)

**Comment by nikmd23** [comment]
HUGE

No worries :wink:

**Comment by stefanjudis** [comment]
Haha... OKay. :D :+1: Thanks. :tada:

**Pull request merged**
