### PR TITLE
add tool "RICG Responsive Images" and Wordpress icon - fix #386

### LINKED ISSUE #386: wp-tevko-responsive-images
https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images

@marcobiedermann 

what about listing tools for common cms systems like wordpress, drupal or typo3.
We would need to add more circles or?

What do you think. :)

### PR DESCRIPTION
**Pull request by marcobiedermann**

### CODE REVIEW

**Comment by marcobiedermann** [comment]
perf-tooling-wordpress

**Comment by stefanjudis** [comment]
@marcobiedermann Nice - but it doesn't look centered does it?

**Comment by marcobiedermann** [comment]
It should be. I implemented it like all the other icons

**Comment by stefanjudis** [comment]
Ja but looms weird... Maybe you can adjust the svg a bit?

**Comment by marcobiedermann** [comment]
perf-tooling-wp

The icon is in the center of the circle. It is just an optical illusion. I would add the icon how it is. Is that ok?

**Comment by stefanjudis** [comment]
Sure. :)

Marco Biedermann <notifications@github.com> schrieb am Mo., 26. Jan. 2015
18:54:

**Comment by stefanjudis** [comment]
@marcobiedermann 

Removed the seperated entry and put it into the `picturefill` tool, because this is what it uses.

Also little side note - whenever we add a new plattform we have to adjust the search. Maybe you can help me to keep track of that. ;)

**Pull request merged**
