### PR TITLE
Update links to sharp-based gulp/grunt tools

### PR DESCRIPTION
**Pull request by lovell**
Hi, I'm the maintainer of sharp - thanks for adding it to perf-tooling in the first place!

I've added a grunt plugin and updated the gulp plugin to point to a slightly better maintained repo.

Ideally this could link to both gulp plugins but I'm not sure there's a way to do that right now.

Cheers,
Lovell

### CODE REVIEW

**Comment by stefanjudis** [comment]
Hey @lovell,

thanks for this. :)

> Ideally this could link to both gulp plugins but I'm not sure there's a way to do that right now.

I'm not really sure about including multiple gulp/grunt plugins. We try to evaluate the one that has more value ( sorry if we missed the better one in this case ;) ) in case there are multiple options. Especially in npm world there are a lot of redundant plugins out there and it may not have to much value to list them all?

What do you think?

**Comment by marcobiedermann** [comment]
@lovell Thank you for your pull request.
I have to agree with @stefanjudis. I prefer including only one plugin per platform. Otherwise the resources will get to much.

**Comment by lovell** [comment]
Thank you for merging and I agree with your quality over quantity principles. I should probably encourage the maintainers of the two sharp-based gulp plugins to pool their efforts.

Are you open to including commercial tools on perf-tooling? I'm currently running a closed-beta of [dimens.io](https://dimens.io/), a real-time, on-demand image resizing/optimising service and would welcome a few more organisations that understand the benefits of web performance. Exactly the sort of people who would be looking at your site :)

**Comment by stefanjudis** [comment]
@lovell 

Sure thing. A PR is very welcome. :)

**Comment by marcobiedermann** [comment]
@lovell We already have an issue about paid services #18. What do you think would be the better option to show that it's not free. If you got other suggestions, feel free to add them to the issue :)

**Comment by stefanjudis** [comment]
Maybe we can agree on another property `paid` and you can already set it to `true` and we'll check how quickly we can display this information. :)

**Pull request merged**
