### PR TITLE
Added grunticon to tools.

### PR DESCRIPTION
**Pull request by fitz0019**
Added grunticon from Filament Group (http://www.grunticon.com/) as a tool.

### CODE REVIEW

**Comment by marcobiedermann** [comment]
@fitz0019 Thank you. Would you add the gulp version as well for us? https://www.npmjs.com/package/gulp-iconify/ :)

**Comment by fitz0019** [comment]
No problem, done! I've add the one you suggested however I think an official one from the Filament Group is in the works. I'll update this whenever it's released.

**Comment by marcobiedermann** [comment]
:+1: Nice. Thanks man. Looks good to me

**Comment by stefanjudis** [comment]
:+1:

**Pull request merged**
