### PR TITLE
add an article "We should optimize images"

### PR DESCRIPTION
**Pull request by 1000ch**
I wrote up [an article](https://medium.com/@1000ch/we-should-optimize-images-8435760e0ec9) about image optimization. :)

### CODE REVIEW

**Comment by stefanjudis** [comment]
Thx @1000ch. Will check it tomorrow.

**Comment by stefanjudis** [comment]
@1000ch 

Same here, I think you didn't set words as length. :)

**Comment by stefanjudis** [comment]
Thanks. :bowtie:

**Comment by 1000ch** [comment]
Thanks a lot! :beers:

**Pull request merged**
