### PR TITLE
🎨 improve gulpfile.js

### PR DESCRIPTION
**Pull request by marcobiedermann**
`package.json`:
- move "gulp" dependencies to devDependencies

`gulpfile.js`
- rename to "gulpfile.babel.js"

`gulpfile.babel.js`
- sort dependencies alphabetically
- prefix "gulp" dependencies
- use ES2015 `const` variables
- use ES2015 template strings
- use ES2015 `import` statement
- use ES2015 fat arrow (`=>`) functions

### CODE REVIEW

**Comment by stefanjudis** [comment]
Hmm... I'm not a big fan of babel on the server side.

You changed the node version to be `v7.x` which means that all these:

- use ES2015 const variables
- use ES2015 template strings
- use ES2015 import statement
- use ES2015 fat arrow (=>) functions

are supported anyways.

Only benefit would be using `import` statements for which afaik there is still final decision if and how these will come into node. (I know that everybody is optimistic about it ;) ).

That said bringing in babel only means a slightly slow down for requiring modules and two more heavy dependencies that will slow down deploys on heroku,

Don't get me wrong I'm totally up for babel in the browser to deal with different browser envs, but here we've got the control and I don't see the need for it.

**Comment by marcobiedermann** [comment]
@stefanjudis I've had some discussions on other projects about it.
I agree on both sides :)

**Comment by marcobiedermann** [comment]
@stefanjudis
I rethought my opinion on this topic :)
When using ES2015 on the server side, I absolutely agree with you but I also suggest moving our front-end code to ES2015 and there we have to use some sort of transpiler.

I suggest using Babel.js on one time compilation usage like gulp task and use native ES2015 in our backend.
What do you think about that?

**Comment by stefanjudis** [comment]
I'm not sure I get that. There are no native ES2015 in node...

**Comment by marcobiedermann** [comment]
Maybe we are talking about different things:
Since Node.js v4+ there are some ES2015 features natively supported by it like (`const`, `let`, template strings, …) See http://node.green/ for full documentation.

As you mentioned `import from` is not implemented in and Node.js version yet.

**Comment by stefanjudis** [comment]
Exactly. :) So babel for Frontend and gulp/server native, right?

**Comment by stefanjudis** [comment]
LGTM.

**Pull request merged**
