### PR TITLE
tools/ruxit

### PR DESCRIPTION
**Pull request by delMar43**
Please, pull :smiley:
For any questions, you can reach me at martingu1979 - at - gmail dot com

### CODE REVIEW

**Comment by stefanjudis** [comment]
can you limit the number of tags. usually we've got 2-3 tags per entry.

**Comment by delMar43** [comment]
sure, done

**Comment by delMar43** [comment]
Sorry, any idea what's broken? The Travis CI output didn't yield any usable information for me :-(

**Comment by stefanjudis** [comment]
Looking good now?

There is only a validator for JSON running on travis.

**Comment by stefanjudis** [comment]
but anyways. fine for me. :) :+1:

**Comment by delMar43** [comment]
Great, thanks!

**Comment by stefanjudis** [comment]
Anytime. :)

**Pull request merged**
