### PR TITLE
add courses section - fix #729

### LINKED ISSUE #729: Add course section
As discussed in #711 a course section would make sense. :)

### PR DESCRIPTION
**Pull request by radibit**

### CODE REVIEW

**Comment by stefanjudis** [comment]
Now when I think of it might make sense, to also indicate if it's free?

What do you think? 

Looking good so far. :bowtie:

**Comment by radibit** [comment]
Yep. I was thinking of the same property as well. Ok, I will added it :-) Thanks.

**Comment by stefanjudis** [comment]
Cool!

Radimir Bitsov <notifications@github.com> schrieb am So., 5. Juli 2015 um
22:50 Uhr:

**Comment by stefanjudis** [comment]
@radibit 

For `tools` we use the payment indication the other way around.

https://github.com/stefanjudis/perf-tooling/blob/master/templates/partials/lists/tools.tpl#L13

We might wanna follow this?

**Comment by radibit** [comment]
@stefanjudis 

OK, it depends if we want to put more focus on the free courses or display indication when it's premium one.

However I can see your point and will change it to follow the same logic as tools.

**Comment by stefanjudis** [comment]
> OK, it depends if we want to put more focus on the free courses or display indication when it's premium one.

This is purely visual and is not connected to how we store the data, or? :bowtie:

**Comment by radibit** [comment]
Yes, it's purely visual.

I forgot to put `isPaid` back to `false` after I tested it.

**Comment by stefanjudis** [comment]
:+1:

**Pull request merged**
