### PR TITLE
add Keepfast to tools

### PR DESCRIPTION
**Pull request by atilafassina**
very promising tool by @davidsonfellipe for integrating multiple performance indicators in a single interface

### CODE REVIEW

**Comment by marcobiedermann** [comment]
:+1: Looks great, I have to test it! Thank you!

**Comment by stefanjudis** [comment]
nice. :) thanks @atilafassina 

will work on it probably on the weekend.

Thanks so much for your contribution. :)

**Comment by davidsonfellipe** [comment]
@atilafassina thankyou by share the keepfast. =) @stefanjudis thankyou by accept.

**Comment by stefanjudis** [comment]
@davidsonfellipe anytime. :)

Maybe want to ping me when you add great stuff to awesome-wpo. ;)

**Pull request merged**
