### PR TITLE
Feature/181 add browsersync

### PR DESCRIPTION
**Pull request by stefanjudis**
Allright - browsersync landed.

Everything can now be started by `npm start`. :)

One thing to mention. I had to put in a delay because whenever we change something in the assets the express server has to be restarted. Played around with it a bit and set it to 1sec now.

It's reacting to changes in templates, less and JS files. :)

Let me know what you think of that.

@marcobiedermann @radibit @marhigh

### CODE REVIEW

**Comment by marcobiedermann** [comment]
Does not work quite well on my end. Browsersync works (scrolling in multiple browsers) but only after a refresh of the site. Developing and live reloading seams to have some trouble. The page is loading forever, no live browser refreshing.
@radibit @marhigh Could you test is too. Maybe it is just a problem on my machine.

**Comment by stefanjudis** [comment]
@marcobiedermann 

I'll check it again. :)

**Comment by stefanjudis** [comment]
@marcobiedermann can you check again?

**Comment by radibit** [comment]
@stefanjudis 

Unfortunately I didn't succeed starting the application with ``` npm start ``` receiving an error of a missing  module:

```console
Error: Cannot find module 'defaults'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/rbit/Projects/perf-tooling/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/vinyl-fs/lib/src/index.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
Tried on node v0.10.37 and v0.11.14

The ``` node app.js ``` command run the app successfully.

**Comment by stefanjudis** [comment]
Did you do a fresh npm install?

Radimir Bitsov <notifications@github.com> schrieb am Fr., 20. März 2015
00:27:

**Comment by radibit** [comment]
Yes, tried several times on clean node_modules state.

**Comment by marcobiedermann** [comment]
@stefanjudis This does not work for me either. Also browser does not open automatically. I have to type in `localhost:3000` and `localhost:4000`

**Comment by stefanjudis** [comment]
Hmm, okay I'll give it another shot then. :(

**Pull request closed without merging**
