### PR TITLE
fix #916 - add "Owning your performance: RAIL" video

### LINKED ISSUE #916: Owning your performance: RAIL
https://www.youtube.com/watch?v=w0O2znkSBXA

### PR DESCRIPTION
**Pull request by marcobiedermann**

### CODE REVIEW

**Comment by stefanjudis** [comment]
@marcobiedermann I think this is more something for our new audits section. :)
Can you move it there?

Would be cool when @paulirish could provide the link to the slides so that we can check if we missed an audit?

**Comment by stefanjudis** [comment]
Closing here. ;)

**Comment by paulirish** [comment]
slides https://docs.google.com/presentation/d/1zTx63aICzj47K2RZzeGdQAXdmCAQ3yBkXSaU_uF69KU/edit?usp=sharing

**Comment by paulirish** [comment]
er. better link for slides: https://docs.google.com/presentation/d/1x0W4hmScGSL2f_1i8puBrpheHHzsBLb0lROkJ6vruks/present?slide=id.g6497df4fb_1_40

**Comment by stefanjudis** [comment]
@paulirish Thanks for the link. :)

JFYI when checking the audits the last 2 links are unfortunately not publicly accessible ( SFGate.com & m.yelp ).

**Pull request closed without merging**
