### PR TITLE
Feature/334 modal deluxe

### PR DESCRIPTION
**Pull request by stefanjudis**

### CODE REVIEW

**Comment by stefanjudis** [comment]
@marcobiedermann @radibit @marhigh 

still waiting for feedback by some one. :)

**Comment by marcobiedermann** [comment]
Look good. I like it :)

**Comment by stefanjudis** [comment]
@marcobiedermann I'd like to have a "normal" link included... This is the only thing what bothers me still. We should give the users the ability to go there when wished.

What do you think?

**Comment by radibit** [comment]
@stefanjudis @marcobiedermann It looks really nice! :smiley: 

I found only one thing - during the modal loading animation I can still scroll up and down. Then after the resource is loaded the position on the background is fixed, though that is true only for the videos ( I can still scroll on the slide page ). Of course this is really a minor thing, I wanted just to share with you.

**Comment by marcobiedermann** [comment]
I've fixed all merged conflicts and adjusted some class names to fit the updated css.

@stefanjudis What do you think about this solution for opening a video / slide in a new tab?

perf-tooling-modal

I like it a lot. Does not distract the user too much.
I just did this quickly in Photoshop, if you all agree on this one @stefanjudis could you please add this to the template and I will add the CSS afterwards.

**Comment by stefanjudis** [comment]
Yeah I'm up for it. :bowtie: 

You'll get the link probably tomorrow. :)

Can we also put some effort in this link in over list.

screenshot 2015-06-04 00 47 41

I'd really like to keep it because it shortens the way to new tab link, if user wants it.
What do you think? It only looks a bit "sad" and misplaced atm.

**Pull request merged**
