### PR TITLE
Create performanceanalyser

### PR DESCRIPTION
**Pull request by alexpainter**

### CODE REVIEW

**Comment by marcobiedermann** [comment]
@alexpainter Thank you, could you please indent using two spaces?!

**Comment by marcobiedermann** [comment]
@alexpainter Perfect, thanks man!

**Comment by alexpainter** [comment]
Thank you! And apologies for the earlier blunder – I did actually read the guidelines, then obviously managed to completely ignore them.

**Comment by marcobiedermann** [comment]
@alexpainter No problem at all!

**Pull request merged**
