### PR TITLE
Feature/608 external svg

### PR DESCRIPTION
**Pull request by marcobiedermann**
Tested in Chrome, Firefox, IE 11 and Chrome on iPhone. Works fine :)

### CODE REVIEW

**Comment by stefanjudis** [comment]
@marcobiedermann 

Cool stuff and great improvement. 

The svg file should be referenced from CDN then. 

Unfortunately this means, that it also needs to be hashed e.g. `icons-djfklaösd.svg` because Fastly is caching everything forever in their cloud.

**Comment by marcobiedermann** [comment]
@stefanjudis This should do it! :D

**Comment by stefanjudis** [comment]
Yeah. :+1: For now this is fine. :)

But we should go away from query param invalidation to the proper way, as this way is not as reliable as giving a new file name. 

As said @radibit radibit implemented already the nicer way. :)

**Comment by stefanjudis** [comment]
@marcobiedermann 

I'll fix the coding style then when merged into master.

But we agreed that

```
css  : md5( fs.readFileSync( './public/main.css', 'utf8' ) ),
  js    : md5( fs.readFileSync( './public/tooling.js', 'utf8' ) )
  js  : md5( fs.readFileSync( './public/tooling.js', 'utf8' ) ),
  svg  : md5( fs.readFileSync( './public/icons.svg', 'utf8' ) )
```

should be

```
css  : md5( fs.readFileSync( './public/main.css', 'utf8' ) ),
  js   : md5( fs.readFileSync( './public/tooling.js', 'utf8' ) )
  js   : md5( fs.readFileSync( './public/tooling.js', 'utf8' ) ),
  svg  : md5( fs.readFileSync( './public/icons.svg', 'utf8' ) )
```

**Comment by marcobiedermann** [comment]
Sure, you are right. Fixed it!

**Comment by stefanjudis** [comment]
Ja, there are two more, but as said I can also fix it, when it's merged into master.

**Comment by marcobiedermann** [comment]
Alright

**Comment by stefanjudis** [comment]
:+1: 

cool stuff! great work. :)

**Pull request merged**
