### PR TITLE
Add performance tool

### PR DESCRIPTION
**Pull request by jaymitripp**
Add dotcom-monitor under "Tools"

# Hey there!

Thanks for contributing to perf-tooling!

Please make sure that you followed the following conventions:

- [x] your commits follow the [gitmoji](https://gitmoji.carloscuesta.me/) convention 
- [x] the build on travis succeeds
- [x] your changes align with the rules in the [CONTRIBUTING.MD](./CONTRIBUTING.md)

**Note:** For all commits dealing with resources, we decided to use the :memo: emoji for commit messages.

And that's it. Thanks! ;)

### CODE REVIEW

**Comment by paulirish** [comment]
free trial behind a sign up form? not very accessible. :/

**Comment by jaymitripp** [comment]
So does that mean it cannot be added to the list?

**Comment by marcobiedermann** [comment]
@jaymitripp 
Thank you for your contribution.
Could you please change the type from `"grunt"` to `"service"` and add a property `"isPaid": true` to it?!

Thanks

**Comment by stefanjudis** [comment]
@jaymitripp Closing due to inactivity. :)

**Pull request closed without merging**
