### PR TITLE
📝 add "Sloth" - fix #1350

### LINKED ISSUE #1350: Add sloth
Hi guys,

I've built chrome extension for throttling page loading speed - https://github.com/denar90/sloth
It was born after [tweeter discussion](https://twitter.com/denar90_/status/964612738235469825).

Would you be interested in adding this one?

### PR DESCRIPTION
**Pull request by denar90**
Heyo 👋  Fixing #1350

### CODE REVIEW

**Comment by stefanjudis** [comment]
I think it should be chrome or? 

https://github.com/stefanjudis/perf-tooling/blob/master/data/tools/cssdig.json#L3-L5

**Comment by denar90** [comment]
I've updated, do you wanna me delete https://github.com/denar90/perf-tooling/blob/9f88030a0d5074a7447c9c36871343c442434253/data/tools/sloth.json#L3-L5 ?

**Comment by stefanjudis** [comment]
That would be great as it's not a bookmarked, or? :blush:

**Comment by stefanjudis** [comment]
You accidentally committed another file? :)

**Comment by denar90** [comment]
Sorry for that, switching between pc's became tough sometimes...

**Comment by stefanjudis** [comment]
No worries. :)

**Pull request merged**
